site_name: Template
plugins:
  - search
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.path
    - navigation.top
  palette: 
    - scheme: default
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
