[project]
name = "Template"
version = "1.2.0"
description = "Template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mike==2.1.3",
    "mkdocs==1.6.1",
    "mkdocs-material==9.5.49",
]
